In [14]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [13]:
(X_train, y_train) , (X_test, y_test) = keras.datasets.mnist.load_data()

In [42]:
print(len(X_train))
print(len(X_test))
X_train.shape

60000
10000


(60000, 28, 28)

In [22]:
X_train = X_train / 255
X_test = X_test / 255

In [80]:
X_train_flattened = X_train.reshape(len(X_train), 28*28)
X_test_flattened = X_test.reshape(len(X_test), 28*28)
X_train_flattened.shape

(60000, 784)

#Model 1 (model_1)
(No hidden layers, sigmoid act. func., adam optimizer)

In [45]:
model_1 = keras.Sequential([
    keras.layers.Dense(10, input_shape=(784,), activation='sigmoid')
])

model_1.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model_1.fit(X_train_flattened, y_train, epochs=6)

Epoch 1/6
1875/1875 [==============================] - 3s 2ms/step - loss: 0.4705 - accuracy: 0.8770
Epoch 2/6
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3041 - accuracy: 0.9148
Epoch 3/6
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2835 - accuracy: 0.9209
Epoch 4/6
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2735 - accuracy: 0.9239
Epoch 5/6
1875/1875 [==============================] - 3s 2ms/step - loss: 0.2669 - accuracy: 0.9256
Epoch 6/6
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2622 - accuracy: 0.9275


In [28]:
model_1.evaluate(X_test_flattened, y_test)

313/313 [==============================] - 1s 1ms/step - loss: 0.2666 - accuracy: 0.9270


[0.2665571868419647, 0.9269999861717224]

In [46]:
y_predicted = model_1.predict(X_test_flattened)

313/313 [==============================] - 0s 1ms/step


In [49]:
y_predicted_labels = [np.argmax(i) for i in y_predicted]
y_predicted_labels[:10]

[7, 2, 1, 0, 4, 1, 4, 9, 6, 9]

In [34]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=y_predicted_labels)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 959,    0,    1,    2,    0,    7,    6,    2,    3,    0],
       [   0, 1110,    3,    2,    0,    1,    4,    2,   13,    0],
       [   3,    8,  920,   17,    9,    5,   13,    9,   45,    3],
       [   1,    0,   20,  920,    1,   20,    2,   10,   26,   10],
       [   1,    1,    3,    1,  924,    0,   11,    2,   10,   29],
       [   7,    3,    3,   37,   11,  773,   14,    5,   32,    7],
       [   9,    3,    8,    1,    7,   12,  912,    2,    4,    0],
       [   1,    6,   24,    4,   11,    1,    0,  932,    4,   45],
       [   4,    6,    7,   19,    9,   19,    8,    3,  889,   10],
       [  10,    7,    1,    7,   29,    6,    0,   10,    8,  931]],
      dtype=int32)>

# Model 2 (model_2)
(1 Hidden layer with 100 nodes & relu act. func.) (Output layer with sigmoid act. func.) ( 5 epochs)

In [50]:
model_2 = keras.Sequential([
    keras.layers.Dense(100, input_shape=(784,), activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')
])

model_2.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model_2.fit(X_train_flattened, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2694 - accuracy: 0.9240
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1231 - accuracy: 0.9644
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0861 - accuracy: 0.9739
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0656 - accuracy: 0.9799
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0516 - accuracy: 0.9842


In [51]:
model_2.evaluate(X_test_flattened,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0788 - accuracy: 0.9767


[0.07877012342214584, 0.9767000079154968]

In [52]:
cm_2 = tf.math.confusion_matrix(labels=y_test,predictions=y_predicted_labels)
cm_2

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 965,    0,    1,    2,    0,    4,    5,    2,    1,    0],
       [   0, 1118,    3,    2,    0,    1,    4,    2,    5,    0],
       [   7,   12,  926,   15,    9,    3,   13,   12,   32,    3],
       [   3,    0,   20,  927,    0,   19,    2,   13,   18,    8],
       [   1,    1,    3,    1,  915,    0,   11,    4,    7,   39],
       [   9,    3,    2,   37,   11,  769,   19,    8,   27,    7],
       [   9,    3,    3,    1,    7,   11,  921,    2,    1,    0],
       [   2,    6,   22,    3,   10,    1,    0,  950,    1,   33],
       [   9,   12,    8,   22,    9,   28,   10,   13,  853,   10],
       [  11,    7,    1,   11,   26,    7,    0,   25,    4,  917]],
      dtype=int32)>

# Model 3 (model_3)
(1 Hidden layer with 100 nodes & relu act. func.) (Output layer with sigmoid act. func.) (10 epochs)

In [69]:
model_3 = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(100, activation='relu'),
    keras.layers.Dense(10, activation='sigmoid')
])

model_3.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

model_3.fit(X_train, y_train, epochs=10)

Epoch 1/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2776 - accuracy: 0.9216
Epoch 2/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1286 - accuracy: 0.9618
Epoch 3/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0902 - accuracy: 0.9730
Epoch 4/10
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0676 - accuracy: 0.9797
Epoch 5/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.0547 - accuracy: 0.9834
Epoch 6/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0442 - accuracy: 0.9860
Epoch 7/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0352 - accuracy: 0.9889
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0292 - accuracy: 0.9912
Epoch 9/10
1875/1875 [==============================] - 6s 3ms/step - loss: 0.0247 - accuracy: 0.9922
Epoch 10/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.019

In [83]:
model_3.evaluate(X_test,y_test)

313/313 [==============================] - 1s 2ms/step - loss: 0.0843 - accuracy: 0.9761


[0.08425591886043549, 0.9761000275611877]

# Model 4 (model_4) **Submission**

In [85]:
model_4 = keras.Sequential([
    keras.layers.Flatten(input_shape=(28, 28)),
    keras.layers.Dense(256, activation='relu'),
    # keras.layers.Dropout(0.5),
    keras.layers.Dense(128, activation='relu'),
    # keras.layers.Dropout(0.5),
    keras.layers.Dense(64, activation='relu'),
    # keras.layers.Dropout(0.5),
    keras.layers.Dense(10, activation='softmax')
])
model_4.compile(optimizer="adam",
                loss='sparse_categorical_crossentropy',
                metrics=['accuracy'])


model_4.fit(X_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2163 - accuracy: 0.9349
Epoch 2/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0943 - accuracy: 0.9712
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0662 - accuracy: 0.9794
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0537 - accuracy: 0.9827
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0412 - accuracy: 0.9864


In [86]:
model_4.evaluate(X_test,y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.0759 - accuracy: 0.9792


[0.07588322460651398, 0.979200005531311]